sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t kawn12/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true kawn12/docker-react-app npm run test -- --coverage
  - echo $AWS_ACCESS_KEY
  - echo $AWS_SECRET_ACCESS_KEY

deploy:
  provider: elasticbeanstalk
  region:  "ap-northeast-1"
  app:  "docker-react-app"
  env:  "Dockerreactapp-env1"
  bucket_name: "elasticbeanstalk-ap-northeast-1-834574396743"
  bucket_path: "docker-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY    
  secret_access_key: $AWS_SECRET_ACCESS_KEY